runtime: nodejs14
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65

# Define environment variables if needed (optional).
env_variables:
  NODE_ENV: 'production'

# Define the entrypoint for the application.
entrypoint: npm start

# Static file handlers.
handlers:
- url: /images
  static_dir: public/images
- url: /javascripts
  static_dir: public/javascripts
- url: /(.*\.(ico|jpg|png|css|js))$
  static_files: public/\1
  upload: public/.*\.(ico|jpg|png|css|js)$

# Handle all other URLs with the application.
- url: /.*
  script: auto
