runtime: go113

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

instance_class: F2

network:
  instance_tag: go-app
  name: default
  subnetwork_name: default

beta_settings:
  cloud_sql_instances: <your-cloud-sql-instance-connection-name>

env_variables:
  PORT: "8080"
  DB_USER: <your-db-user>
  DB_PASS: <your-db-pass>
  DB_NAME: <your-db-name>
